[platformio]
default_envs = usb

[env]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
lib_deps =
  ArduinoOTA
  knolleary/PubSubClient@^2.8
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.15
build_flags = -I../shared
extra_scripts = pre:../shared/version.py
monitor_speed = 115200

[env:usb]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
